#!/usr/bin/env python

import io
import json
import sys


def main():
    f = None
    msgonly = "-m" in sys.argv or "--message-only" in sys.argv
    if len(sys.argv) == 1 or (msgonly and len(sys.argv) == 2):
        f = sys.stdin
    else:
        f = io.open(sys.argv[-1])

    for line in f.readlines():
        if msgonly:
            try:
                print(json.loads(line)["msg"])
            except ValueError:
                pass
        else:
            try:
                print(json.loads(json.loads(line), indent=4))
            except ValueError:
                pass

if __name__ == "__main__":
    main()
