#!/usr/bin/env python

import io
import json
import pprint
import sys


def main():
    f = None
    if len(sys.argv) == 1:
        f = sys.stdin
    else:
        f = io.open(sys.argv[1])

    for line in f.readlines():
        try:
            pprint.pprint(json.loads(line))
        except ValueError:
            pass

if __name__ == "__main__":
    main()
